# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Generate Release Artifacts

on:
  push:
    branches: [ "main", "dev" ]
    tags: ['v*']
  pull_request:
    branches: [ "main" ]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build Current Annualized Return
        uses: psethwick/go-cross-build@1.2.0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: 'cmd/currentReturn'
          name: 'currentreturn'
          compress: 'true'
          dest: 'bin'
      - name: Build Stock Client
        uses: psethwick/go-cross-build@1.2.0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: 'cmd/stockClient'
          name: 'stockclient'
          compress: 'true'
          dest: 'bin'
      - name: Build Target Annualized Returns
        uses: psethwick/go-cross-build@1.2.0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: 'cmd/targetReturn'
          name: 'targetreturn'
          compress: 'true'
          dest: 'bin'
      # Upload Build Files
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        warn: "No file found at bin/*.tar.gz"
        with:
          path: bin/*.tar.gz
          compression-level: 6
          overwrite: true