# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Generate Release Artifacts

on:
  push:
    branches: [ "main", "dev" ]
    tags: ['v*']
  pull_request:
    branches: [ "main" ]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build Stock Client
        run: make release

      # Upload Build Files
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          path: bin/*.tar.gz
          warn: "No file found at bin/*.tar.gz"
          overwrite: true
      - name: Upload a Build Artifact 2
        uses: actions/upload-artifact@v4.3.0
        with:
          path: bin/*.zip
          warn: "No file found at bin/*.zip"
          overwrite: true